// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: tenki/cloud/workspace/v1beta1/secrets.proto

package workspacev1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/LuxorLabs/tenki-sdk-go/sandbox/internal/proto/tenki/cloud/workspace/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkspaceSecretsServiceName is the fully-qualified name of the WorkspaceSecretsService service.
	WorkspaceSecretsServiceName = "tenki.cloud.workspace.v1beta1.WorkspaceSecretsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkspaceSecretsServiceCreateSecretProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's CreateSecret RPC.
	WorkspaceSecretsServiceCreateSecretProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/CreateSecret"
	// WorkspaceSecretsServiceUpdateSecretProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's UpdateSecret RPC.
	WorkspaceSecretsServiceUpdateSecretProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/UpdateSecret"
	// WorkspaceSecretsServiceGetSecretProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's GetSecret RPC.
	WorkspaceSecretsServiceGetSecretProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/GetSecret"
	// WorkspaceSecretsServiceListSecretsProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's ListSecrets RPC.
	WorkspaceSecretsServiceListSecretsProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/ListSecrets"
	// WorkspaceSecretsServiceListSecretVersionsProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's ListSecretVersions RPC.
	WorkspaceSecretsServiceListSecretVersionsProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/ListSecretVersions"
	// WorkspaceSecretsServiceRevokeSecretProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's RevokeSecret RPC.
	WorkspaceSecretsServiceRevokeSecretProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/RevokeSecret"
	// WorkspaceSecretsServiceDeleteSecretProcedure is the fully-qualified name of the
	// WorkspaceSecretsService's DeleteSecret RPC.
	WorkspaceSecretsServiceDeleteSecretProcedure = "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/DeleteSecret"
)

// WorkspaceSecretsServiceClient is a client for the
// tenki.cloud.workspace.v1beta1.WorkspaceSecretsService service.
type WorkspaceSecretsServiceClient interface {
	CreateSecret(context.Context, *connect.Request[v1beta1.CreateSecretRequest]) (*connect.Response[v1beta1.CreateSecretResponse], error)
	UpdateSecret(context.Context, *connect.Request[v1beta1.UpdateSecretRequest]) (*connect.Response[v1beta1.UpdateSecretResponse], error)
	GetSecret(context.Context, *connect.Request[v1beta1.GetSecretRequest]) (*connect.Response[v1beta1.GetSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[v1beta1.ListSecretsRequest]) (*connect.Response[v1beta1.ListSecretsResponse], error)
	ListSecretVersions(context.Context, *connect.Request[v1beta1.ListSecretVersionsRequest]) (*connect.Response[v1beta1.ListSecretVersionsResponse], error)
	RevokeSecret(context.Context, *connect.Request[v1beta1.RevokeSecretRequest]) (*connect.Response[v1beta1.RevokeSecretResponse], error)
	DeleteSecret(context.Context, *connect.Request[v1beta1.DeleteSecretRequest]) (*connect.Response[v1beta1.DeleteSecretResponse], error)
}

// NewWorkspaceSecretsServiceClient constructs a client for the
// tenki.cloud.workspace.v1beta1.WorkspaceSecretsService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkspaceSecretsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkspaceSecretsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workspaceSecretsServiceMethods := v1beta1.File_tenki_cloud_workspace_v1beta1_secrets_proto.Services().ByName("WorkspaceSecretsService").Methods()
	return &workspaceSecretsServiceClient{
		createSecret: connect.NewClient[v1beta1.CreateSecretRequest, v1beta1.CreateSecretResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceCreateSecretProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("CreateSecret")),
			connect.WithClientOptions(opts...),
		),
		updateSecret: connect.NewClient[v1beta1.UpdateSecretRequest, v1beta1.UpdateSecretResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceUpdateSecretProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("UpdateSecret")),
			connect.WithClientOptions(opts...),
		),
		getSecret: connect.NewClient[v1beta1.GetSecretRequest, v1beta1.GetSecretResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceGetSecretProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("GetSecret")),
			connect.WithClientOptions(opts...),
		),
		listSecrets: connect.NewClient[v1beta1.ListSecretsRequest, v1beta1.ListSecretsResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceListSecretsProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("ListSecrets")),
			connect.WithClientOptions(opts...),
		),
		listSecretVersions: connect.NewClient[v1beta1.ListSecretVersionsRequest, v1beta1.ListSecretVersionsResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceListSecretVersionsProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("ListSecretVersions")),
			connect.WithClientOptions(opts...),
		),
		revokeSecret: connect.NewClient[v1beta1.RevokeSecretRequest, v1beta1.RevokeSecretResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceRevokeSecretProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("RevokeSecret")),
			connect.WithClientOptions(opts...),
		),
		deleteSecret: connect.NewClient[v1beta1.DeleteSecretRequest, v1beta1.DeleteSecretResponse](
			httpClient,
			baseURL+WorkspaceSecretsServiceDeleteSecretProcedure,
			connect.WithSchema(workspaceSecretsServiceMethods.ByName("DeleteSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workspaceSecretsServiceClient implements WorkspaceSecretsServiceClient.
type workspaceSecretsServiceClient struct {
	createSecret       *connect.Client[v1beta1.CreateSecretRequest, v1beta1.CreateSecretResponse]
	updateSecret       *connect.Client[v1beta1.UpdateSecretRequest, v1beta1.UpdateSecretResponse]
	getSecret          *connect.Client[v1beta1.GetSecretRequest, v1beta1.GetSecretResponse]
	listSecrets        *connect.Client[v1beta1.ListSecretsRequest, v1beta1.ListSecretsResponse]
	listSecretVersions *connect.Client[v1beta1.ListSecretVersionsRequest, v1beta1.ListSecretVersionsResponse]
	revokeSecret       *connect.Client[v1beta1.RevokeSecretRequest, v1beta1.RevokeSecretResponse]
	deleteSecret       *connect.Client[v1beta1.DeleteSecretRequest, v1beta1.DeleteSecretResponse]
}

// CreateSecret calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.CreateSecret.
func (c *workspaceSecretsServiceClient) CreateSecret(ctx context.Context, req *connect.Request[v1beta1.CreateSecretRequest]) (*connect.Response[v1beta1.CreateSecretResponse], error) {
	return c.createSecret.CallUnary(ctx, req)
}

// UpdateSecret calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.UpdateSecret.
func (c *workspaceSecretsServiceClient) UpdateSecret(ctx context.Context, req *connect.Request[v1beta1.UpdateSecretRequest]) (*connect.Response[v1beta1.UpdateSecretResponse], error) {
	return c.updateSecret.CallUnary(ctx, req)
}

// GetSecret calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.GetSecret.
func (c *workspaceSecretsServiceClient) GetSecret(ctx context.Context, req *connect.Request[v1beta1.GetSecretRequest]) (*connect.Response[v1beta1.GetSecretResponse], error) {
	return c.getSecret.CallUnary(ctx, req)
}

// ListSecrets calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecrets.
func (c *workspaceSecretsServiceClient) ListSecrets(ctx context.Context, req *connect.Request[v1beta1.ListSecretsRequest]) (*connect.Response[v1beta1.ListSecretsResponse], error) {
	return c.listSecrets.CallUnary(ctx, req)
}

// ListSecretVersions calls
// tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecretVersions.
func (c *workspaceSecretsServiceClient) ListSecretVersions(ctx context.Context, req *connect.Request[v1beta1.ListSecretVersionsRequest]) (*connect.Response[v1beta1.ListSecretVersionsResponse], error) {
	return c.listSecretVersions.CallUnary(ctx, req)
}

// RevokeSecret calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.RevokeSecret.
func (c *workspaceSecretsServiceClient) RevokeSecret(ctx context.Context, req *connect.Request[v1beta1.RevokeSecretRequest]) (*connect.Response[v1beta1.RevokeSecretResponse], error) {
	return c.revokeSecret.CallUnary(ctx, req)
}

// DeleteSecret calls tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.DeleteSecret.
func (c *workspaceSecretsServiceClient) DeleteSecret(ctx context.Context, req *connect.Request[v1beta1.DeleteSecretRequest]) (*connect.Response[v1beta1.DeleteSecretResponse], error) {
	return c.deleteSecret.CallUnary(ctx, req)
}

// WorkspaceSecretsServiceHandler is an implementation of the
// tenki.cloud.workspace.v1beta1.WorkspaceSecretsService service.
type WorkspaceSecretsServiceHandler interface {
	CreateSecret(context.Context, *connect.Request[v1beta1.CreateSecretRequest]) (*connect.Response[v1beta1.CreateSecretResponse], error)
	UpdateSecret(context.Context, *connect.Request[v1beta1.UpdateSecretRequest]) (*connect.Response[v1beta1.UpdateSecretResponse], error)
	GetSecret(context.Context, *connect.Request[v1beta1.GetSecretRequest]) (*connect.Response[v1beta1.GetSecretResponse], error)
	ListSecrets(context.Context, *connect.Request[v1beta1.ListSecretsRequest]) (*connect.Response[v1beta1.ListSecretsResponse], error)
	ListSecretVersions(context.Context, *connect.Request[v1beta1.ListSecretVersionsRequest]) (*connect.Response[v1beta1.ListSecretVersionsResponse], error)
	RevokeSecret(context.Context, *connect.Request[v1beta1.RevokeSecretRequest]) (*connect.Response[v1beta1.RevokeSecretResponse], error)
	DeleteSecret(context.Context, *connect.Request[v1beta1.DeleteSecretRequest]) (*connect.Response[v1beta1.DeleteSecretResponse], error)
}

// NewWorkspaceSecretsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkspaceSecretsServiceHandler(svc WorkspaceSecretsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workspaceSecretsServiceMethods := v1beta1.File_tenki_cloud_workspace_v1beta1_secrets_proto.Services().ByName("WorkspaceSecretsService").Methods()
	workspaceSecretsServiceCreateSecretHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceCreateSecretProcedure,
		svc.CreateSecret,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("CreateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceUpdateSecretHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceUpdateSecretProcedure,
		svc.UpdateSecret,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("UpdateSecret")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceGetSecretHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceGetSecretProcedure,
		svc.GetSecret,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("GetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceListSecretsHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceListSecretsProcedure,
		svc.ListSecrets,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("ListSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceListSecretVersionsHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceListSecretVersionsProcedure,
		svc.ListSecretVersions,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("ListSecretVersions")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceRevokeSecretHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceRevokeSecretProcedure,
		svc.RevokeSecret,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("RevokeSecret")),
		connect.WithHandlerOptions(opts...),
	)
	workspaceSecretsServiceDeleteSecretHandler := connect.NewUnaryHandler(
		WorkspaceSecretsServiceDeleteSecretProcedure,
		svc.DeleteSecret,
		connect.WithSchema(workspaceSecretsServiceMethods.ByName("DeleteSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/tenki.cloud.workspace.v1beta1.WorkspaceSecretsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkspaceSecretsServiceCreateSecretProcedure:
			workspaceSecretsServiceCreateSecretHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceUpdateSecretProcedure:
			workspaceSecretsServiceUpdateSecretHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceGetSecretProcedure:
			workspaceSecretsServiceGetSecretHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceListSecretsProcedure:
			workspaceSecretsServiceListSecretsHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceListSecretVersionsProcedure:
			workspaceSecretsServiceListSecretVersionsHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceRevokeSecretProcedure:
			workspaceSecretsServiceRevokeSecretHandler.ServeHTTP(w, r)
		case WorkspaceSecretsServiceDeleteSecretProcedure:
			workspaceSecretsServiceDeleteSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkspaceSecretsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkspaceSecretsServiceHandler struct{}

func (UnimplementedWorkspaceSecretsServiceHandler) CreateSecret(context.Context, *connect.Request[v1beta1.CreateSecretRequest]) (*connect.Response[v1beta1.CreateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.CreateSecret is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) UpdateSecret(context.Context, *connect.Request[v1beta1.UpdateSecretRequest]) (*connect.Response[v1beta1.UpdateSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.UpdateSecret is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) GetSecret(context.Context, *connect.Request[v1beta1.GetSecretRequest]) (*connect.Response[v1beta1.GetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.GetSecret is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) ListSecrets(context.Context, *connect.Request[v1beta1.ListSecretsRequest]) (*connect.Response[v1beta1.ListSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecrets is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) ListSecretVersions(context.Context, *connect.Request[v1beta1.ListSecretVersionsRequest]) (*connect.Response[v1beta1.ListSecretVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecretVersions is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) RevokeSecret(context.Context, *connect.Request[v1beta1.RevokeSecretRequest]) (*connect.Response[v1beta1.RevokeSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.RevokeSecret is not implemented"))
}

func (UnimplementedWorkspaceSecretsServiceHandler) DeleteSecret(context.Context, *connect.Request[v1beta1.DeleteSecretRequest]) (*connect.Response[v1beta1.DeleteSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.DeleteSecret is not implemented"))
}
