// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenki/sandbox/v1/secret_injection.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A nonsecret placeholder is secrets://NAME; a binding grants its use only at this request location.
type SecretRequestBinding struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SecretName     string                 `protobuf:"bytes,2,opt,name=secret_name,json=secretName,proto3" json:"secret_name,omitempty"`
	Origin         string                 `protobuf:"bytes,4,opt,name=origin,proto3" json:"origin,omitempty"`
	Methods        []string               `protobuf:"bytes,5,rep,name=methods,proto3" json:"methods,omitempty"`
	PathPrefix     string                 `protobuf:"bytes,6,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	Header         string                 `protobuf:"bytes,7,opt,name=header,proto3" json:"header,omitempty"`
	QueryParameter string                 `protobuf:"bytes,8,opt,name=query_parameter,json=queryParameter,proto3" json:"query_parameter,omitempty"`
	// RFC 6901 pointer to a JSON string field, for example /credentials/token.
	JsonPointer   string `protobuf:"bytes,9,opt,name=json_pointer,json=jsonPointer,proto3" json:"json_pointer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretRequestBinding) Reset() {
	*x = SecretRequestBinding{}
	mi := &file_tenki_sandbox_v1_secret_injection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretRequestBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretRequestBinding) ProtoMessage() {}

func (x *SecretRequestBinding) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_secret_injection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretRequestBinding.ProtoReflect.Descriptor instead.
func (*SecretRequestBinding) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_secret_injection_proto_rawDescGZIP(), []int{0}
}

func (x *SecretRequestBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretRequestBinding) GetSecretName() string {
	if x != nil {
		return x.SecretName
	}
	return ""
}

func (x *SecretRequestBinding) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SecretRequestBinding) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *SecretRequestBinding) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *SecretRequestBinding) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *SecretRequestBinding) GetQueryParameter() string {
	if x != nil {
		return x.QueryParameter
	}
	return ""
}

func (x *SecretRequestBinding) GetJsonPointer() string {
	if x != nil {
		return x.JsonPointer
	}
	return ""
}

var File_tenki_sandbox_v1_secret_injection_proto protoreflect.FileDescriptor

const file_tenki_sandbox_v1_secret_injection_proto_rawDesc = "" +
	"\n" +
	"'tenki/sandbox/v1/secret_injection.proto\x12\x10tenki.sandbox.v1\"\x91\x02\n" +
	"\x14SecretRequestBinding\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsecret_name\x18\x02 \x01(\tR\n" +
	"secretName\x12\x16\n" +
	"\x06origin\x18\x04 \x01(\tR\x06origin\x12\x18\n" +
	"\amethods\x18\x05 \x03(\tR\amethods\x12\x1f\n" +
	"\vpath_prefix\x18\x06 \x01(\tR\n" +
	"pathPrefix\x12\x16\n" +
	"\x06header\x18\a \x01(\tR\x06header\x12'\n" +
	"\x0fquery_parameter\x18\b \x01(\tR\x0equeryParameter\x12!\n" +
	"\fjson_pointer\x18\t \x01(\tR\vjsonPointerJ\x04\b\x03\x10\x04R\aversionB\xe3\x01\n" +
	"\x14com.tenki.sandbox.v1B\x14SecretInjectionProtoP\x01ZSgithub.com/LuxorLabs/tenki-sdk-go/sandbox/internal/proto/tenki/sandbox/v1;sandboxv1\xa2\x02\x03TSX\xaa\x02\x10Tenki.Sandbox.V1\xca\x02\x10Tenki\\Sandbox\\V1\xe2\x02\x1cTenki\\Sandbox\\V1\\GPBMetadata\xea\x02\x12Tenki::Sandbox::V1b\x06proto3"

var (
	file_tenki_sandbox_v1_secret_injection_proto_rawDescOnce sync.Once
	file_tenki_sandbox_v1_secret_injection_proto_rawDescData []byte
)

func file_tenki_sandbox_v1_secret_injection_proto_rawDescGZIP() []byte {
	file_tenki_sandbox_v1_secret_injection_proto_rawDescOnce.Do(func() {
		file_tenki_sandbox_v1_secret_injection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_secret_injection_proto_rawDesc), len(file_tenki_sandbox_v1_secret_injection_proto_rawDesc)))
	})
	return file_tenki_sandbox_v1_secret_injection_proto_rawDescData
}

var file_tenki_sandbox_v1_secret_injection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tenki_sandbox_v1_secret_injection_proto_goTypes = []any{
	(*SecretRequestBinding)(nil), // 0: tenki.sandbox.v1.SecretRequestBinding
}
var file_tenki_sandbox_v1_secret_injection_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tenki_sandbox_v1_secret_injection_proto_init() }
func file_tenki_sandbox_v1_secret_injection_proto_init() {
	if File_tenki_sandbox_v1_secret_injection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_secret_injection_proto_rawDesc), len(file_tenki_sandbox_v1_secret_injection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenki_sandbox_v1_secret_injection_proto_goTypes,
		DependencyIndexes: file_tenki_sandbox_v1_secret_injection_proto_depIdxs,
		MessageInfos:      file_tenki_sandbox_v1_secret_injection_proto_msgTypes,
	}.Build()
	File_tenki_sandbox_v1_secret_injection_proto = out.File
	file_tenki_sandbox_v1_secret_injection_proto_goTypes = nil
	file_tenki_sandbox_v1_secret_injection_proto_depIdxs = nil
}
