// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenki/sandbox/v1/secret_file.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// File declarations contain references and nonsecret configuration only.
type RuntimeSecretReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Placeholder   bool                   `protobuf:"varint,2,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSecretReference) Reset() {
	*x = RuntimeSecretReference{}
	mi := &file_tenki_sandbox_v1_secret_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSecretReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSecretReference) ProtoMessage() {}

func (x *RuntimeSecretReference) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_secret_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSecretReference.ProtoReflect.Descriptor instead.
func (*RuntimeSecretReference) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_secret_file_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeSecretReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeSecretReference) GetPlaceholder() bool {
	if x != nil {
		return x.Placeholder
	}
	return false
}

type RuntimeSecretFile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Types that are valid to be assigned to Format:
	//
	//	*RuntimeSecretFile_Raw
	//	*RuntimeSecretFile_Source
	//	*RuntimeSecretFile_Content
	Format        isRuntimeSecretFile_Format `protobuf_oneof:"format"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeSecretFile) Reset() {
	*x = RuntimeSecretFile{}
	mi := &file_tenki_sandbox_v1_secret_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSecretFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSecretFile) ProtoMessage() {}

func (x *RuntimeSecretFile) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_sandbox_v1_secret_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSecretFile.ProtoReflect.Descriptor instead.
func (*RuntimeSecretFile) Descriptor() ([]byte, []int) {
	return file_tenki_sandbox_v1_secret_file_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeSecretFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RuntimeSecretFile) GetFormat() isRuntimeSecretFile_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *RuntimeSecretFile) GetRaw() *RuntimeSecretReference {
	if x != nil {
		if x, ok := x.Format.(*RuntimeSecretFile_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *RuntimeSecretFile) GetSource() string {
	if x != nil {
		if x, ok := x.Format.(*RuntimeSecretFile_Source); ok {
			return x.Source
		}
	}
	return ""
}

func (x *RuntimeSecretFile) GetContent() string {
	if x != nil {
		if x, ok := x.Format.(*RuntimeSecretFile_Content); ok {
			return x.Content
		}
	}
	return ""
}

type isRuntimeSecretFile_Format interface {
	isRuntimeSecretFile_Format()
}

type RuntimeSecretFile_Raw struct {
	Raw *RuntimeSecretReference `protobuf:"bytes,2,opt,name=raw,proto3,oneof"`
}

type RuntimeSecretFile_Source struct {
	// Build-time path inside the guest image; captured without resolving secrets.
	Source string `protobuf:"bytes,3,opt,name=source,proto3,oneof"`
}

type RuntimeSecretFile_Content struct {
	// Unresolved text uploaded by a caller or captured during a template build.
	Content string `protobuf:"bytes,4,opt,name=content,proto3,oneof"`
}

func (*RuntimeSecretFile_Raw) isRuntimeSecretFile_Format() {}

func (*RuntimeSecretFile_Source) isRuntimeSecretFile_Format() {}

func (*RuntimeSecretFile_Content) isRuntimeSecretFile_Format() {}

var File_tenki_sandbox_v1_secret_file_proto protoreflect.FileDescriptor

const file_tenki_sandbox_v1_secret_file_proto_rawDesc = "" +
	"\n" +
	"\"tenki/sandbox/v1/secret_file.proto\x12\x10tenki.sandbox.v1\"N\n" +
	"\x16RuntimeSecretReference\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vplaceholder\x18\x02 \x01(\bR\vplaceholder\"\xa5\x01\n" +
	"\x11RuntimeSecretFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12<\n" +
	"\x03raw\x18\x02 \x01(\v2(.tenki.sandbox.v1.RuntimeSecretReferenceH\x00R\x03raw\x12\x18\n" +
	"\x06source\x18\x03 \x01(\tH\x00R\x06source\x12\x1a\n" +
	"\acontent\x18\x04 \x01(\tH\x00R\acontentB\b\n" +
	"\x06formatB\xde\x01\n" +
	"\x14com.tenki.sandbox.v1B\x0fSecretFileProtoP\x01ZSgithub.com/LuxorLabs/tenki-sdk-go/sandbox/internal/proto/tenki/sandbox/v1;sandboxv1\xa2\x02\x03TSX\xaa\x02\x10Tenki.Sandbox.V1\xca\x02\x10Tenki\\Sandbox\\V1\xe2\x02\x1cTenki\\Sandbox\\V1\\GPBMetadata\xea\x02\x12Tenki::Sandbox::V1b\x06proto3"

var (
	file_tenki_sandbox_v1_secret_file_proto_rawDescOnce sync.Once
	file_tenki_sandbox_v1_secret_file_proto_rawDescData []byte
)

func file_tenki_sandbox_v1_secret_file_proto_rawDescGZIP() []byte {
	file_tenki_sandbox_v1_secret_file_proto_rawDescOnce.Do(func() {
		file_tenki_sandbox_v1_secret_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_secret_file_proto_rawDesc), len(file_tenki_sandbox_v1_secret_file_proto_rawDesc)))
	})
	return file_tenki_sandbox_v1_secret_file_proto_rawDescData
}

var file_tenki_sandbox_v1_secret_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tenki_sandbox_v1_secret_file_proto_goTypes = []any{
	(*RuntimeSecretReference)(nil), // 0: tenki.sandbox.v1.RuntimeSecretReference
	(*RuntimeSecretFile)(nil),      // 1: tenki.sandbox.v1.RuntimeSecretFile
}
var file_tenki_sandbox_v1_secret_file_proto_depIdxs = []int32{
	0, // 0: tenki.sandbox.v1.RuntimeSecretFile.raw:type_name -> tenki.sandbox.v1.RuntimeSecretReference
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tenki_sandbox_v1_secret_file_proto_init() }
func file_tenki_sandbox_v1_secret_file_proto_init() {
	if File_tenki_sandbox_v1_secret_file_proto != nil {
		return
	}
	file_tenki_sandbox_v1_secret_file_proto_msgTypes[1].OneofWrappers = []any{
		(*RuntimeSecretFile_Raw)(nil),
		(*RuntimeSecretFile_Source)(nil),
		(*RuntimeSecretFile_Content)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenki_sandbox_v1_secret_file_proto_rawDesc), len(file_tenki_sandbox_v1_secret_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tenki_sandbox_v1_secret_file_proto_goTypes,
		DependencyIndexes: file_tenki_sandbox_v1_secret_file_proto_depIdxs,
		MessageInfos:      file_tenki_sandbox_v1_secret_file_proto_msgTypes,
	}.Build()
	File_tenki_sandbox_v1_secret_file_proto = out.File
	file_tenki_sandbox_v1_secret_file_proto_goTypes = nil
	file_tenki_sandbox_v1_secret_file_proto_depIdxs = nil
}
