// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tenki/cloud/workspace/v1beta1/secrets.proto

package workspacev1beta1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretDeliveryMode int32

const (
	SecretDeliveryMode_SECRET_DELIVERY_MODE_UNSPECIFIED         SecretDeliveryMode = 0
	SecretDeliveryMode_SECRET_DELIVERY_MODE_GUEST_AND_INJECTION SecretDeliveryMode = 1
	SecretDeliveryMode_SECRET_DELIVERY_MODE_INJECTION_ONLY      SecretDeliveryMode = 2
)

// Enum value maps for SecretDeliveryMode.
var (
	SecretDeliveryMode_name = map[int32]string{
		0: "SECRET_DELIVERY_MODE_UNSPECIFIED",
		1: "SECRET_DELIVERY_MODE_GUEST_AND_INJECTION",
		2: "SECRET_DELIVERY_MODE_INJECTION_ONLY",
	}
	SecretDeliveryMode_value = map[string]int32{
		"SECRET_DELIVERY_MODE_UNSPECIFIED":         0,
		"SECRET_DELIVERY_MODE_GUEST_AND_INJECTION": 1,
		"SECRET_DELIVERY_MODE_INJECTION_ONLY":      2,
	}
)

func (x SecretDeliveryMode) Enum() *SecretDeliveryMode {
	p := new(SecretDeliveryMode)
	*p = x
	return p
}

func (x SecretDeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretDeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[0].Descriptor()
}

func (SecretDeliveryMode) Type() protoreflect.EnumType {
	return &file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[0]
}

func (x SecretDeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretDeliveryMode.Descriptor instead.
func (SecretDeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{0}
}

type SecretDestinationMode int32

const (
	SecretDestinationMode_SECRET_DESTINATION_MODE_UNSPECIFIED SecretDestinationMode = 0
	SecretDestinationMode_SECRET_DESTINATION_MODE_UNSET       SecretDestinationMode = 1
	SecretDestinationMode_SECRET_DESTINATION_MODE_ALLOWLIST   SecretDestinationMode = 2
	SecretDestinationMode_SECRET_DESTINATION_MODE_ALLOW_ANY   SecretDestinationMode = 3
)

// Enum value maps for SecretDestinationMode.
var (
	SecretDestinationMode_name = map[int32]string{
		0: "SECRET_DESTINATION_MODE_UNSPECIFIED",
		1: "SECRET_DESTINATION_MODE_UNSET",
		2: "SECRET_DESTINATION_MODE_ALLOWLIST",
		3: "SECRET_DESTINATION_MODE_ALLOW_ANY",
	}
	SecretDestinationMode_value = map[string]int32{
		"SECRET_DESTINATION_MODE_UNSPECIFIED": 0,
		"SECRET_DESTINATION_MODE_UNSET":       1,
		"SECRET_DESTINATION_MODE_ALLOWLIST":   2,
		"SECRET_DESTINATION_MODE_ALLOW_ANY":   3,
	}
)

func (x SecretDestinationMode) Enum() *SecretDestinationMode {
	p := new(SecretDestinationMode)
	*p = x
	return p
}

func (x SecretDestinationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretDestinationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[1].Descriptor()
}

func (SecretDestinationMode) Type() protoreflect.EnumType {
	return &file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[1]
}

func (x SecretDestinationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretDestinationMode.Descriptor instead.
func (SecretDestinationMode) EnumDescriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{1}
}

type SecretSortField int32

const (
	// Orders by secret ID, the only order cursor pagination supports.
	SecretSortField_SECRET_SORT_FIELD_UNSPECIFIED SecretSortField = 0
	SecretSortField_SECRET_SORT_FIELD_NAME        SecretSortField = 1
	// Active before revoked.
	SecretSortField_SECRET_SORT_FIELD_STATUS SecretSortField = 2
	// Runtime allowed before injection only.
	SecretSortField_SECRET_SORT_FIELD_ACCESS     SecretSortField = 3
	SecretSortField_SECRET_SORT_FIELD_UPDATED_AT SecretSortField = 4
)

// Enum value maps for SecretSortField.
var (
	SecretSortField_name = map[int32]string{
		0: "SECRET_SORT_FIELD_UNSPECIFIED",
		1: "SECRET_SORT_FIELD_NAME",
		2: "SECRET_SORT_FIELD_STATUS",
		3: "SECRET_SORT_FIELD_ACCESS",
		4: "SECRET_SORT_FIELD_UPDATED_AT",
	}
	SecretSortField_value = map[string]int32{
		"SECRET_SORT_FIELD_UNSPECIFIED": 0,
		"SECRET_SORT_FIELD_NAME":        1,
		"SECRET_SORT_FIELD_STATUS":      2,
		"SECRET_SORT_FIELD_ACCESS":      3,
		"SECRET_SORT_FIELD_UPDATED_AT":  4,
	}
)

func (x SecretSortField) Enum() *SecretSortField {
	p := new(SecretSortField)
	*p = x
	return p
}

func (x SecretSortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretSortField) Descriptor() protoreflect.EnumDescriptor {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[2].Descriptor()
}

func (SecretSortField) Type() protoreflect.EnumType {
	return &file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes[2]
}

func (x SecretSortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretSortField.Descriptor instead.
func (SecretSortField) EnumDescriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{2}
}

type SecretPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryMode    SecretDeliveryMode     `protobuf:"varint,1,opt,name=delivery_mode,json=deliveryMode,proto3,enum=tenki.cloud.workspace.v1beta1.SecretDeliveryMode" json:"delivery_mode,omitempty"`
	DestinationMode SecretDestinationMode  `protobuf:"varint,2,opt,name=destination_mode,json=destinationMode,proto3,enum=tenki.cloud.workspace.v1beta1.SecretDestinationMode" json:"destination_mode,omitempty"`
	AllowedHosts    []string               `protobuf:"bytes,3,rep,name=allowed_hosts,json=allowedHosts,proto3" json:"allowed_hosts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SecretPolicy) Reset() {
	*x = SecretPolicy{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretPolicy) ProtoMessage() {}

func (x *SecretPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretPolicy.ProtoReflect.Descriptor instead.
func (*SecretPolicy) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{0}
}

func (x *SecretPolicy) GetDeliveryMode() SecretDeliveryMode {
	if x != nil {
		return x.DeliveryMode
	}
	return SecretDeliveryMode_SECRET_DELIVERY_MODE_UNSPECIFIED
}

func (x *SecretPolicy) GetDestinationMode() SecretDestinationMode {
	if x != nil {
		return x.DestinationMode
	}
	return SecretDestinationMode_SECRET_DESTINATION_MODE_UNSPECIFIED
}

func (x *SecretPolicy) GetAllowedHosts() []string {
	if x != nil {
		return x.AllowedHosts
	}
	return nil
}

// Metadata only. Values and encrypted values are never returned publicly.
type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ActiveVersion uint32                 `protobuf:"varint,4,opt,name=active_version,json=activeVersion,proto3" json:"active_version,omitempty"`
	Revision      uint32                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Policy        *SecretPolicy          `protobuf:"bytes,6,opt,name=policy,proto3" json:"policy,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{1}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetActiveVersion() uint32 {
	if x != nil {
		return x.ActiveVersion
	}
	return 0
}

func (x *Secret) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Secret) GetPolicy() *SecretPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *Secret) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Secret) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *Secret) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type SecretVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretVersion) Reset() {
	*x = SecretVersion{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretVersion) ProtoMessage() {}

func (x *SecretVersion) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretVersion.ProtoReflect.Descriptor instead.
func (*SecretVersion) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{2}
}

func (x *SecretVersion) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SecretVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretVersion) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Policy        *SecretPolicy          `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *CreateSecretRequest) GetPolicy() *SecretPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *CreateSecretRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// Omitted value retains the active version; present empty bytes creates an empty value.
type UpdateSecretRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SecretId         string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Value            []byte                 `protobuf:"bytes,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Policy           *SecretPolicy          `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	ExpectedRevision uint32                 `protobuf:"varint,5,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	RequestId        string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ActiveVersion    *uint32                `protobuf:"varint,7,opt,name=active_version,json=activeVersion,proto3,oneof" json:"active_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *UpdateSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *UpdateSecretRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *UpdateSecretRequest) GetPolicy() *SecretPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *UpdateSecretRequest) GetExpectedRevision() uint32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *UpdateSecretRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateSecretRequest) GetActiveVersion() uint32 {
	if x != nil && x.ActiveVersion != nil {
		return *x.ActiveVersion
	}
	return 0
}

type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{8}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type ListSecretsRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	PageSize    uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Continues from next_cursor; cannot be combined with search, sort_by or offset.
	Cursor string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Case-insensitive substring match on the secret name.
	Search string          `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	SortBy SecretSortField `protobuf:"varint,5,opt,name=sort_by,json=sortBy,proto3,enum=tenki.cloud.workspace.v1beta1.SecretSortField" json:"sort_by,omitempty"`
	// Ignored when sort_by is unspecified.
	SortDesc bool `protobuf:"varint,6,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	// Matching secrets to skip, for numbered pages.
	Offset        uint32 `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListSecretsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSecretsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSecretsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListSecretsRequest) GetSortBy() SecretSortField {
	if x != nil {
		return x.SortBy
	}
	return SecretSortField_SECRET_SORT_FIELD_UNSPECIFIED
}

func (x *ListSecretsRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

func (x *ListSecretsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSecretsResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Secrets []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// Set only when more secrets follow in the default order without a search.
	NextCursor string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	// Secrets matching the search across all pages.
	TotalCount    uint32 `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{10}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

func (x *ListSecretsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListSecretsResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ListSecretVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsRequest) Reset() {
	*x = ListSecretVersionsRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsRequest) ProtoMessage() {}

func (x *ListSecretVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{11}
}

func (x *ListSecretVersionsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListSecretVersionsRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *ListSecretVersionsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListSecretVersionsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListSecretVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*SecretVersion       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretVersionsResponse) Reset() {
	*x = ListSecretVersionsResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretVersionsResponse) ProtoMessage() {}

func (x *ListSecretVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretVersionsResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{12}
}

func (x *ListSecretVersionsResponse) GetVersions() []*SecretVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListSecretVersionsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// Omitted version revokes the entire secret. Revocation is irreversible.
type RevokeSecretRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SecretId         string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Version          *uint32                `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ExpectedRevision uint32                 `protobuf:"varint,4,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	RequestId        string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RevokeSecretRequest) Reset() {
	*x = RevokeSecretRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSecretRequest) ProtoMessage() {}

func (x *RevokeSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSecretRequest.ProtoReflect.Descriptor instead.
func (*RevokeSecretRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RevokeSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *RevokeSecretRequest) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *RevokeSecretRequest) GetExpectedRevision() uint32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *RevokeSecretRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RevokeSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSecretResponse) Reset() {
	*x = RevokeSecretResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSecretResponse) ProtoMessage() {}

func (x *RevokeSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSecretResponse.ProtoReflect.Descriptor instead.
func (*RevokeSecretResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

type DeleteSecretRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId      string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SecretId         string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	ExpectedRevision uint32                 `protobuf:"varint,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	RequestId        string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteSecretRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *DeleteSecretRequest) GetExpectedRevision() uint32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *DeleteSecretRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_tenki_cloud_workspace_v1beta1_secrets_proto protoreflect.FileDescriptor

const file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDesc = "" +
	"\n" +
	"+tenki/cloud/workspace/v1beta1/secrets.proto\x12\x1dtenki.cloud.workspace.v1beta1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n" +
	"\fSecretPolicy\x12V\n" +
	"\rdelivery_mode\x18\x01 \x01(\x0e21.tenki.cloud.workspace.v1beta1.SecretDeliveryModeR\fdeliveryMode\x12_\n" +
	"\x10destination_mode\x18\x02 \x01(\x0e24.tenki.cloud.workspace.v1beta1.SecretDestinationModeR\x0fdestinationMode\x12#\n" +
	"\rallowed_hosts\x18\x03 \x03(\tR\fallowedHosts\"\xc3\x03\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\x0eactive_version\x18\x04 \x01(\rR\ractiveVersion\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\rR\brevision\x12C\n" +
	"\x06policy\x18\x06 \x01(\v2+.tenki.cloud.workspace.v1beta1.SecretPolicyR\x06policy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x9f\x01\n" +
	"\rSecretVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xd5\x01\n" +
	"\x13CreateSecretRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x03 \x01(\fH\x00R\x05value\x88\x01\x01\x12C\n" +
	"\x06policy\x18\x04 \x01(\v2+.tenki.cloud.workspace.v1beta1.SecretPolicyR\x06policy\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestIdB\b\n" +
	"\x06_value\"U\n" +
	"\x14CreateSecretResponse\x12=\n" +
	"\x06secret\x18\x01 \x01(\v2%.tenki.cloud.workspace.v1beta1.SecretR\x06secret\"\xca\x02\n" +
	"\x13UpdateSecretRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x19\n" +
	"\x05value\x18\x03 \x01(\fH\x00R\x05value\x88\x01\x01\x12C\n" +
	"\x06policy\x18\x04 \x01(\v2+.tenki.cloud.workspace.v1beta1.SecretPolicyR\x06policy\x12+\n" +
	"\x11expected_revision\x18\x05 \x01(\rR\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12*\n" +
	"\x0eactive_version\x18\a \x01(\rH\x01R\ractiveVersion\x88\x01\x01B\b\n" +
	"\x06_valueB\x11\n" +
	"\x0f_active_version\"U\n" +
	"\x14UpdateSecretResponse\x12=\n" +
	"\x06secret\x18\x01 \x01(\v2%.tenki.cloud.workspace.v1beta1.SecretR\x06secret\"R\n" +
	"\x10GetSecretRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\"R\n" +
	"\x11GetSecretResponse\x12=\n" +
	"\x06secret\x18\x01 \x01(\v2%.tenki.cloud.workspace.v1beta1.SecretR\x06secret\"\x82\x02\n" +
	"\x12ListSecretsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\x12G\n" +
	"\asort_by\x18\x05 \x01(\x0e2..tenki.cloud.workspace.v1beta1.SecretSortFieldR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\x06 \x01(\bR\bsortDesc\x12\x16\n" +
	"\x06offset\x18\a \x01(\rR\x06offset\"\x98\x01\n" +
	"\x13ListSecretsResponse\x12?\n" +
	"\asecrets\x18\x01 \x03(\v2%.tenki.cloud.workspace.v1beta1.SecretR\asecrets\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\rR\n" +
	"totalCount\"\x90\x01\n" +
	"\x19ListSecretVersionsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"\x87\x01\n" +
	"\x1aListSecretVersionsResponse\x12H\n" +
	"\bversions\x18\x01 \x03(\v2,.tenki.cloud.workspace.v1beta1.SecretVersionR\bversions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xcc\x01\n" +
	"\x13RevokeSecretRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\rH\x00R\aversion\x88\x01\x01\x12+\n" +
	"\x11expected_revision\x18\x04 \x01(\rR\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestIdB\n" +
	"\n" +
	"\b_version\"U\n" +
	"\x14RevokeSecretResponse\x12=\n" +
	"\x06secret\x18\x01 \x01(\v2%.tenki.cloud.workspace.v1beta1.SecretR\x06secret\"\xa1\x01\n" +
	"\x13DeleteSecretRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12+\n" +
	"\x11expected_revision\x18\x03 \x01(\rR\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"U\n" +
	"\x14DeleteSecretResponse\x12=\n" +
	"\x06secret\x18\x01 \x01(\v2%.tenki.cloud.workspace.v1beta1.SecretR\x06secret*\x91\x01\n" +
	"\x12SecretDeliveryMode\x12$\n" +
	" SECRET_DELIVERY_MODE_UNSPECIFIED\x10\x00\x12,\n" +
	"(SECRET_DELIVERY_MODE_GUEST_AND_INJECTION\x10\x01\x12'\n" +
	"#SECRET_DELIVERY_MODE_INJECTION_ONLY\x10\x02*\xb1\x01\n" +
	"\x15SecretDestinationMode\x12'\n" +
	"#SECRET_DESTINATION_MODE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSECRET_DESTINATION_MODE_UNSET\x10\x01\x12%\n" +
	"!SECRET_DESTINATION_MODE_ALLOWLIST\x10\x02\x12%\n" +
	"!SECRET_DESTINATION_MODE_ALLOW_ANY\x10\x03*\xae\x01\n" +
	"\x0fSecretSortField\x12!\n" +
	"\x1dSECRET_SORT_FIELD_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SECRET_SORT_FIELD_NAME\x10\x01\x12\x1c\n" +
	"\x18SECRET_SORT_FIELD_STATUS\x10\x02\x12\x1c\n" +
	"\x18SECRET_SORT_FIELD_ACCESS\x10\x03\x12 \n" +
	"\x1cSECRET_SORT_FIELD_UPDATED_AT\x10\x042\xef\x06\n" +
	"\x17WorkspaceSecretsService\x12w\n" +
	"\fCreateSecret\x122.tenki.cloud.workspace.v1beta1.CreateSecretRequest\x1a3.tenki.cloud.workspace.v1beta1.CreateSecretResponse\x12w\n" +
	"\fUpdateSecret\x122.tenki.cloud.workspace.v1beta1.UpdateSecretRequest\x1a3.tenki.cloud.workspace.v1beta1.UpdateSecretResponse\x12n\n" +
	"\tGetSecret\x12/.tenki.cloud.workspace.v1beta1.GetSecretRequest\x1a0.tenki.cloud.workspace.v1beta1.GetSecretResponse\x12t\n" +
	"\vListSecrets\x121.tenki.cloud.workspace.v1beta1.ListSecretsRequest\x1a2.tenki.cloud.workspace.v1beta1.ListSecretsResponse\x12\x89\x01\n" +
	"\x12ListSecretVersions\x128.tenki.cloud.workspace.v1beta1.ListSecretVersionsRequest\x1a9.tenki.cloud.workspace.v1beta1.ListSecretVersionsResponse\x12w\n" +
	"\fRevokeSecret\x122.tenki.cloud.workspace.v1beta1.RevokeSecretRequest\x1a3.tenki.cloud.workspace.v1beta1.RevokeSecretResponse\x12w\n" +
	"\fDeleteSecret\x122.tenki.cloud.workspace.v1beta1.DeleteSecretRequest\x1a3.tenki.cloud.workspace.v1beta1.DeleteSecretResponseB\xb1\x02\n" +
	"!com.tenki.cloud.workspace.v1beta1B\fSecretsProtoP\x01Zggithub.com/LuxorLabs/tenki-sdk-go/sandbox/internal/proto/tenki/cloud/workspace/v1beta1;workspacev1beta1\xa2\x02\x03TCW\xaa\x02\x1dTenki.Cloud.Workspace.V1beta1\xca\x02\x1dTenki\\Cloud\\Workspace\\V1beta1\xe2\x02)Tenki\\Cloud\\Workspace\\V1beta1\\GPBMetadata\xea\x02 Tenki::Cloud::Workspace::V1beta1b\x06proto3"

var (
	file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescOnce sync.Once
	file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescData []byte
)

func file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescGZIP() []byte {
	file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescOnce.Do(func() {
		file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDesc), len(file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDesc)))
	})
	return file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDescData
}

var file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_tenki_cloud_workspace_v1beta1_secrets_proto_goTypes = []any{
	(SecretDeliveryMode)(0),            // 0: tenki.cloud.workspace.v1beta1.SecretDeliveryMode
	(SecretDestinationMode)(0),         // 1: tenki.cloud.workspace.v1beta1.SecretDestinationMode
	(SecretSortField)(0),               // 2: tenki.cloud.workspace.v1beta1.SecretSortField
	(*SecretPolicy)(nil),               // 3: tenki.cloud.workspace.v1beta1.SecretPolicy
	(*Secret)(nil),                     // 4: tenki.cloud.workspace.v1beta1.Secret
	(*SecretVersion)(nil),              // 5: tenki.cloud.workspace.v1beta1.SecretVersion
	(*CreateSecretRequest)(nil),        // 6: tenki.cloud.workspace.v1beta1.CreateSecretRequest
	(*CreateSecretResponse)(nil),       // 7: tenki.cloud.workspace.v1beta1.CreateSecretResponse
	(*UpdateSecretRequest)(nil),        // 8: tenki.cloud.workspace.v1beta1.UpdateSecretRequest
	(*UpdateSecretResponse)(nil),       // 9: tenki.cloud.workspace.v1beta1.UpdateSecretResponse
	(*GetSecretRequest)(nil),           // 10: tenki.cloud.workspace.v1beta1.GetSecretRequest
	(*GetSecretResponse)(nil),          // 11: tenki.cloud.workspace.v1beta1.GetSecretResponse
	(*ListSecretsRequest)(nil),         // 12: tenki.cloud.workspace.v1beta1.ListSecretsRequest
	(*ListSecretsResponse)(nil),        // 13: tenki.cloud.workspace.v1beta1.ListSecretsResponse
	(*ListSecretVersionsRequest)(nil),  // 14: tenki.cloud.workspace.v1beta1.ListSecretVersionsRequest
	(*ListSecretVersionsResponse)(nil), // 15: tenki.cloud.workspace.v1beta1.ListSecretVersionsResponse
	(*RevokeSecretRequest)(nil),        // 16: tenki.cloud.workspace.v1beta1.RevokeSecretRequest
	(*RevokeSecretResponse)(nil),       // 17: tenki.cloud.workspace.v1beta1.RevokeSecretResponse
	(*DeleteSecretRequest)(nil),        // 18: tenki.cloud.workspace.v1beta1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),       // 19: tenki.cloud.workspace.v1beta1.DeleteSecretResponse
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_tenki_cloud_workspace_v1beta1_secrets_proto_depIdxs = []int32{
	0,  // 0: tenki.cloud.workspace.v1beta1.SecretPolicy.delivery_mode:type_name -> tenki.cloud.workspace.v1beta1.SecretDeliveryMode
	1,  // 1: tenki.cloud.workspace.v1beta1.SecretPolicy.destination_mode:type_name -> tenki.cloud.workspace.v1beta1.SecretDestinationMode
	3,  // 2: tenki.cloud.workspace.v1beta1.Secret.policy:type_name -> tenki.cloud.workspace.v1beta1.SecretPolicy
	20, // 3: tenki.cloud.workspace.v1beta1.Secret.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: tenki.cloud.workspace.v1beta1.Secret.updated_at:type_name -> google.protobuf.Timestamp
	20, // 5: tenki.cloud.workspace.v1beta1.Secret.revoked_at:type_name -> google.protobuf.Timestamp
	20, // 6: tenki.cloud.workspace.v1beta1.Secret.deleted_at:type_name -> google.protobuf.Timestamp
	20, // 7: tenki.cloud.workspace.v1beta1.SecretVersion.created_at:type_name -> google.protobuf.Timestamp
	20, // 8: tenki.cloud.workspace.v1beta1.SecretVersion.revoked_at:type_name -> google.protobuf.Timestamp
	3,  // 9: tenki.cloud.workspace.v1beta1.CreateSecretRequest.policy:type_name -> tenki.cloud.workspace.v1beta1.SecretPolicy
	4,  // 10: tenki.cloud.workspace.v1beta1.CreateSecretResponse.secret:type_name -> tenki.cloud.workspace.v1beta1.Secret
	3,  // 11: tenki.cloud.workspace.v1beta1.UpdateSecretRequest.policy:type_name -> tenki.cloud.workspace.v1beta1.SecretPolicy
	4,  // 12: tenki.cloud.workspace.v1beta1.UpdateSecretResponse.secret:type_name -> tenki.cloud.workspace.v1beta1.Secret
	4,  // 13: tenki.cloud.workspace.v1beta1.GetSecretResponse.secret:type_name -> tenki.cloud.workspace.v1beta1.Secret
	2,  // 14: tenki.cloud.workspace.v1beta1.ListSecretsRequest.sort_by:type_name -> tenki.cloud.workspace.v1beta1.SecretSortField
	4,  // 15: tenki.cloud.workspace.v1beta1.ListSecretsResponse.secrets:type_name -> tenki.cloud.workspace.v1beta1.Secret
	5,  // 16: tenki.cloud.workspace.v1beta1.ListSecretVersionsResponse.versions:type_name -> tenki.cloud.workspace.v1beta1.SecretVersion
	4,  // 17: tenki.cloud.workspace.v1beta1.RevokeSecretResponse.secret:type_name -> tenki.cloud.workspace.v1beta1.Secret
	4,  // 18: tenki.cloud.workspace.v1beta1.DeleteSecretResponse.secret:type_name -> tenki.cloud.workspace.v1beta1.Secret
	6,  // 19: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.CreateSecret:input_type -> tenki.cloud.workspace.v1beta1.CreateSecretRequest
	8,  // 20: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.UpdateSecret:input_type -> tenki.cloud.workspace.v1beta1.UpdateSecretRequest
	10, // 21: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.GetSecret:input_type -> tenki.cloud.workspace.v1beta1.GetSecretRequest
	12, // 22: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecrets:input_type -> tenki.cloud.workspace.v1beta1.ListSecretsRequest
	14, // 23: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecretVersions:input_type -> tenki.cloud.workspace.v1beta1.ListSecretVersionsRequest
	16, // 24: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.RevokeSecret:input_type -> tenki.cloud.workspace.v1beta1.RevokeSecretRequest
	18, // 25: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.DeleteSecret:input_type -> tenki.cloud.workspace.v1beta1.DeleteSecretRequest
	7,  // 26: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.CreateSecret:output_type -> tenki.cloud.workspace.v1beta1.CreateSecretResponse
	9,  // 27: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.UpdateSecret:output_type -> tenki.cloud.workspace.v1beta1.UpdateSecretResponse
	11, // 28: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.GetSecret:output_type -> tenki.cloud.workspace.v1beta1.GetSecretResponse
	13, // 29: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecrets:output_type -> tenki.cloud.workspace.v1beta1.ListSecretsResponse
	15, // 30: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.ListSecretVersions:output_type -> tenki.cloud.workspace.v1beta1.ListSecretVersionsResponse
	17, // 31: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.RevokeSecret:output_type -> tenki.cloud.workspace.v1beta1.RevokeSecretResponse
	19, // 32: tenki.cloud.workspace.v1beta1.WorkspaceSecretsService.DeleteSecret:output_type -> tenki.cloud.workspace.v1beta1.DeleteSecretResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_tenki_cloud_workspace_v1beta1_secrets_proto_init() }
func file_tenki_cloud_workspace_v1beta1_secrets_proto_init() {
	if File_tenki_cloud_workspace_v1beta1_secrets_proto != nil {
		return
	}
	file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[3].OneofWrappers = []any{}
	file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[5].OneofWrappers = []any{}
	file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDesc), len(file_tenki_cloud_workspace_v1beta1_secrets_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tenki_cloud_workspace_v1beta1_secrets_proto_goTypes,
		DependencyIndexes: file_tenki_cloud_workspace_v1beta1_secrets_proto_depIdxs,
		EnumInfos:         file_tenki_cloud_workspace_v1beta1_secrets_proto_enumTypes,
		MessageInfos:      file_tenki_cloud_workspace_v1beta1_secrets_proto_msgTypes,
	}.Build()
	File_tenki_cloud_workspace_v1beta1_secrets_proto = out.File
	file_tenki_cloud_workspace_v1beta1_secrets_proto_goTypes = nil
	file_tenki_cloud_workspace_v1beta1_secrets_proto_depIdxs = nil
}
